spring.application.name=coffeeshop_vigo

# Config MYSQL local
spring.datasource.url = jdbc:mysql://localhost:3306/coffeeshop_vigo
spring.datasource.username = root
spring.datasource.password =

# Config JPA

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true